export const featuredPropertiesData = [
  {
    key: "uk",
    label: "UK",
    properties: [
      {
        _id: "uk1",
        title: "Modern Studio in King's Cross",
        description: "A stylish studio apartment in the heart of King's Cross.",
        noOfRooms: 1,
        images: [
          "https://images.unsplash.com/photo-1721322800607-8c38375eef04?w=400&h=300&fit=crop",
        ],
        price: 450,
        location: {
          latitude: 51.5308,
          longitude: -0.1238,
          address: "King's Cross, London, UK",
        },
        amenities: ["WiFi", "Parking", "Gym"],
        type: "Studio",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 120,
        ratings: 4.8,
        isFeatured: true,
        leaseDuration: "12 months",
        securityDeposit: 900,
        utilitiesIncluded: true,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-01T10:00:00.000Z",
        updatedAt: "2024-06-10T10:00:00.000Z",
        __v: 0,
      },
      {
        _id: "uk2",
        title: "Shared Apartment Near UCL",
        description: "Spacious shared apartment close to UCL campus.",
        noOfRooms: 4,
        images: [
          "https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=400&h=300&fit=crop",
        ],
        price: 320,
        location: {
          latitude: 51.5238,
          longitude: -0.1337,
          address: "Bloomsbury, London, UK",
        },
        amenities: ["WiFi", "Gym"],
        type: "Shared Apartment",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 98,
        ratings: 4.6,
        isFeatured: true,
        leaseDuration: "10 months",
        securityDeposit: 640,
        utilitiesIncluded: false,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-02T11:00:00.000Z",
        updatedAt: "2024-06-10T11:00:00.000Z",
        __v: 0,
      },
      {
        _id: "uk3",
        title: "Luxury Student Housing",
        description: "Premium student housing with all amenities.",
        noOfRooms: 1,
        images: [
          "https://images.unsplash.com/photo-1500673922987-e212871fec22?w=400&h=300&fit=crop",
        ],
        price: 580,
        location: {
          latitude: 51.5054,
          longitude: -0.0235,
          address: "Canary Wharf, London, UK",
        },
        amenities: ["WiFi", "Parking", "Gym"],
        type: "Apartment",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 150,
        ratings: 4.9,
        isFeatured: true,
        leaseDuration: "12 months",
        securityDeposit: 1160,
        utilitiesIncluded: true,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-03T12:00:00.000Z",
        updatedAt: "2024-06-10T12:00:00.000Z",
        __v: 0,
      },
      {
        _id: "uk4",
        title: "Student Village Complex",
        description: "Modern student village with communal spaces.",
        noOfRooms: 3,
        images: [
          "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=400&h=300&fit=crop",
        ],
        price: 380,
        location: {
          latitude: 51.5074,
          longitude: -0.1278,
          address: "City Centre, London, UK",
        },
        amenities: ["WiFi", "Gym"],
        type: "Complex",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 110,
        ratings: 4.7,
        isFeatured: true,
        leaseDuration: "9 months",
        securityDeposit: 760,
        utilitiesIncluded: false,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-04T13:00:00.000Z",
        updatedAt: "2024-06-10T13:00:00.000Z",
        __v: 0,
      },
      {
        _id: "uk5",
        title: "Brighton Beach Apartment",
        description: "Cozy apartment with sea view in Brighton.",
        noOfRooms: 2,
        images: [
          "https://images.unsplash.com/photo-1466442929976-97f336a657be?w=400&h=300&fit=crop",
        ],
        price: 400,
        location: {
          latitude: 50.8225,
          longitude: -0.1372,
          address: "Brighton, UK",
        },
        amenities: ["WiFi", "Parking"],
        type: "Apartment",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 80,
        ratings: 4.5,
        isFeatured: true,
        leaseDuration: "12 months",
        securityDeposit: 800,
        utilitiesIncluded: true,
        petPolicy: "Pets allowed",
        createdAt: "2024-06-05T14:00:00.000Z",
        updatedAt: "2024-06-10T14:00:00.000Z",
        __v: 0,
      },
      {
        _id: "uk6",
        title: "Manchester City Flat",
        description: "Central Manchester flat for students.",
        noOfRooms: 2,
        images: [
          "https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=400&h=300&fit=crop",
        ],
        price: 350,
        location: {
          latitude: 53.4808,
          longitude: -2.2426,
          address: "Manchester, UK",
        },
        amenities: ["WiFi", "Gym"],
        type: "Flat",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 90,
        ratings: 4.4,
        isFeatured: true,
        leaseDuration: "10 months",
        securityDeposit: 700,
        utilitiesIncluded: false,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-06T15:00:00.000Z",
        updatedAt: "2024-06-10T15:00:00.000Z",
        __v: 0,
      },
      {
        _id: "uk7",
        title: "Edinburgh Student Residence",
        description: "Student residence in the heart of Edinburgh.",
        noOfRooms: 1,
        images: [
          "https://images.unsplash.com/photo-1500673922987-e212871fec22?w=400&h=300&fit=crop",
        ],
        price: 370,
        location: {
          latitude: 55.9533,
          longitude: -3.1883,
          address: "Edinburgh, UK",
        },
        amenities: ["WiFi", "Parking"],
        type: "Residence",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 70,
        ratings: 4.3,
        isFeatured: true,
        leaseDuration: "12 months",
        securityDeposit: 740,
        utilitiesIncluded: true,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-07T16:00:00.000Z",
        updatedAt: "2024-06-10T16:00:00.000Z",
        __v: 0,
      },
      {
        _id: "uk8",
        title: "Sheffield Modern Flat",
        description: "Modern flat in Sheffield for students.",
        noOfRooms: 2,
        images: [
          "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=400&h=300&fit=crop",
        ],
        price: 330,
        location: {
          latitude: 53.3811,
          longitude: -1.4701,
          address: "Sheffield, UK",
        },
        amenities: ["WiFi", "Gym"],
        type: "Flat",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 60,
        ratings: 4.2,
        isFeatured: true,
        leaseDuration: "9 months",
        securityDeposit: 660,
        utilitiesIncluded: false,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-08T17:00:00.000Z",
        updatedAt: "2024-06-10T17:00:00.000Z",
        __v: 0,
      },
      {
        _id: "uk9",
        title: "Leeds City Apartment",
        description: "Apartment in Leeds city centre.",
        noOfRooms: 1,
        images: [
          "https://images.unsplash.com/photo-1466442929976-97f336a657be?w=400&h=300&fit=crop",
        ],
        price: 340,
        location: {
          latitude: 53.8008,
          longitude: -1.5491,
          address: "Leeds, UK",
        },
        amenities: ["WiFi", "Parking"],
        type: "Apartment",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 55,
        ratings: 4.1,
        isFeatured: true,
        leaseDuration: "12 months",
        securityDeposit: 680,
        utilitiesIncluded: true,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-09T18:00:00.000Z",
        updatedAt: "2024-06-10T18:00:00.000Z",
        __v: 0,
      },
      {
        _id: "uk10",
        title: "Liverpool Waterfront Studio",
        description: "Studio with waterfront view in Liverpool.",
        noOfRooms: 1,
        images: [
          "https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=400&h=300&fit=crop",
        ],
        price: 360,
        location: {
          latitude: 53.4084,
          longitude: -2.9916,
          address: "Liverpool, UK",
        },
        amenities: ["WiFi", "Gym"],
        type: "Studio",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 65,
        ratings: 4.2,
        isFeatured: true,
        leaseDuration: "10 months",
        securityDeposit: 720,
        utilitiesIncluded: false,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-10T19:00:00.000Z",
        updatedAt: "2024-06-10T19:00:00.000Z",
        __v: 0,
      },
      {
        _id: "uk11",
        title: "Coventry Student Flat",
        description: "Affordable student flat in Coventry.",
        noOfRooms: 2,
        images: [
          "https://images.unsplash.com/photo-1500673922987-e212871fec22?w=400&h=300&fit=crop",
        ],
        price: 310,
        location: {
          latitude: 52.4068,
          longitude: -1.5197,
          address: "Coventry, UK",
        },
        amenities: ["WiFi", "Parking"],
        type: "Flat",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 50,
        ratings: 4.0,
        isFeatured: true,
        leaseDuration: "12 months",
        securityDeposit: 620,
        utilitiesIncluded: true,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-11T20:00:00.000Z",
        updatedAt: "2024-06-11T20:00:00.000Z",
        __v: 0,
      },
      {
        _id: "uk12",
        title: "Nottingham Central Apartment",
        description: "Central apartment in Nottingham for students.",
        noOfRooms: 1,
        images: [
          "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=400&h=300&fit=crop",
        ],
        price: 320,
        location: {
          latitude: 52.9548,
          longitude: -1.1581,
          address: "Nottingham, UK",
        },
        amenities: ["WiFi", "Gym"],
        type: "Apartment",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 45,
        ratings: 4.1,
        isFeatured: true,
        leaseDuration: "9 months",
        securityDeposit: 640,
        utilitiesIncluded: false,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-12T21:00:00.000Z",
        updatedAt: "2024-06-12T21:00:00.000Z",
        __v: 0,
      },
    ],
  },
  {
    key: "australia",
    label: "Australia",
    properties: [
      {
        _id: "au1",
        title: "Sydney Harbour Studio",
        description: "Studio with a view of Sydney Harbour.",
        noOfRooms: 1,
        images: [
          "https://images.unsplash.com/photo-1466442929976-97f336a657be?w=400&h=300&fit=crop",
        ],
        price: 500,
        location: {
          latitude: -33.8688,
          longitude: 151.2093,
          address: "Sydney, Australia",
        },
        amenities: ["WiFi", "Parking", "Gym"],
        type: "Studio",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 130,
        ratings: 4.7,
        isFeatured: true,
        leaseDuration: "12 months",
        securityDeposit: 1000,
        utilitiesIncluded: true,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-01T10:00:00.000Z",
        updatedAt: "2024-06-10T10:00:00.000Z",
        __v: 0,
      },
      {
        _id: "au2",
        title: "Melbourne City Apartment",
        description: "Modern apartment in Melbourne city centre.",
        noOfRooms: 2,
        images: [
          "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=400&h=300&fit=crop",
        ],
        price: 420,
        location: {
          latitude: -37.8136,
          longitude: 144.9631,
          address: "Melbourne, Australia",
        },
        amenities: ["WiFi", "Gym"],
        type: "Apartment",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 110,
        ratings: 4.5,
        isFeatured: true,
        leaseDuration: "10 months",
        securityDeposit: 840,
        utilitiesIncluded: false,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-02T11:00:00.000Z",
        updatedAt: "2024-06-10T11:00:00.000Z",
        __v: 0,
      },
      {
        _id: "au3",
        title: "Brisbane River Flat",
        description: "Flat with river view in Brisbane.",
        noOfRooms: 1,
        images: [
          "https://images.unsplash.com/photo-1500673922987-e212871fec22?w=400&h=300&fit=crop",
        ],
        price: 390,
        location: {
          latitude: -27.4698,
          longitude: 153.0251,
          address: "Brisbane, Australia",
        },
        amenities: ["WiFi", "Parking"],
        type: "Flat",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 90,
        ratings: 4.4,
        isFeatured: true,
        leaseDuration: "12 months",
        securityDeposit: 780,
        utilitiesIncluded: true,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-03T12:00:00.000Z",
        updatedAt: "2024-06-10T12:00:00.000Z",
        __v: 0,
      },
      {
        _id: "au4",
        title: "Perth Student Residence",
        description: "Student residence in Perth city.",
        noOfRooms: 2,
        images: [
          "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=400&h=300&fit=crop",
        ],
        price: 370,
        location: {
          latitude: -31.9505,
          longitude: 115.8605,
          address: "Perth, Australia",
        },
        amenities: ["WiFi", "Gym"],
        type: "Residence",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 80,
        ratings: 4.3,
        isFeatured: true,
        leaseDuration: "9 months",
        securityDeposit: 740,
        utilitiesIncluded: false,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-04T13:00:00.000Z",
        updatedAt: "2024-06-10T13:00:00.000Z",
        __v: 0,
      },
      {
        _id: "au5",
        title: "Adelaide Central Apartment",
        description: "Central apartment in Adelaide for students.",
        noOfRooms: 1,
        images: [
          "https://images.unsplash.com/photo-1466442929976-97f336a657be?w=400&h=300&fit=crop",
        ],
        price: 350,
        location: {
          latitude: -34.9285,
          longitude: 138.6007,
          address: "Adelaide, Australia",
        },
        amenities: ["WiFi", "Parking"],
        type: "Apartment",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 70,
        ratings: 4.2,
        isFeatured: true,
        leaseDuration: "12 months",
        securityDeposit: 700,
        utilitiesIncluded: true,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-05T14:00:00.000Z",
        updatedAt: "2024-06-10T14:00:00.000Z",
        __v: 0,
      },
      {
        _id: "au6",
        title: "Canberra Student Flat",
        description: "Affordable student flat in Canberra.",
        noOfRooms: 2,
        images: [
          "https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=400&h=300&fit=crop",
        ],
        price: 340,
        location: {
          latitude: -35.2809,
          longitude: 149.13,
          address: "Canberra, Australia",
        },
        amenities: ["WiFi", "Gym"],
        type: "Flat",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 60,
        ratings: 4.1,
        isFeatured: true,
        leaseDuration: "10 months",
        securityDeposit: 680,
        utilitiesIncluded: false,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-06T15:00:00.000Z",
        updatedAt: "2024-06-10T15:00:00.000Z",
        __v: 0,
      },
      {
        _id: "au7",
        title: "Gold Coast Beach Studio",
        description: "Studio near the beach in Gold Coast.",
        noOfRooms: 1,
        images: [
          "https://images.unsplash.com/photo-1500673922987-e212871fec22?w=400&h=300&fit=crop",
        ],
        price: 380,
        location: {
          latitude: -28.0167,
          longitude: 153.4,
          address: "Gold Coast, Australia",
        },
        amenities: ["WiFi", "Parking"],
        type: "Studio",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 50,
        ratings: 4.0,
        isFeatured: true,
        leaseDuration: "12 months",
        securityDeposit: 760,
        utilitiesIncluded: true,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-07T16:00:00.000Z",
        updatedAt: "2024-06-10T16:00:00.000Z",
        __v: 0,
      },
      {
        _id: "au8",
        title: "Newcastle City Apartment",
        description: "Apartment in Newcastle city centre.",
        noOfRooms: 2,
        images: [
          "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=400&h=300&fit=crop",
        ],
        price: 360,
        location: {
          latitude: -32.9283,
          longitude: 151.7817,
          address: "Newcastle, Australia",
        },
        amenities: ["WiFi", "Gym"],
        type: "Apartment",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 45,
        ratings: 4.1,
        isFeatured: true,
        leaseDuration: "9 months",
        securityDeposit: 720,
        utilitiesIncluded: false,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-08T17:00:00.000Z",
        updatedAt: "2024-06-10T17:00:00.000Z",
        __v: 0,
      },
      {
        _id: "au9",
        title: "Wollongong Student Residence",
        description: "Student residence in Wollongong.",
        noOfRooms: 1,
        images: [
          "https://images.unsplash.com/photo-1466442929976-97f336a657be?w=400&h=300&fit=crop",
        ],
        price: 330,
        location: {
          latitude: -34.4278,
          longitude: 150.8931,
          address: "Wollongong, Australia",
        },
        amenities: ["WiFi", "Parking"],
        type: "Residence",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 40,
        ratings: 4.0,
        isFeatured: true,
        leaseDuration: "12 months",
        securityDeposit: 660,
        utilitiesIncluded: true,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-09T18:00:00.000Z",
        updatedAt: "2024-06-10T18:00:00.000Z",
        __v: 0,
      },
      {
        _id: "au10",
        title: "Hobart Central Flat",
        description: "Central flat in Hobart for students.",
        noOfRooms: 2,
        images: [
          "https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=400&h=300&fit=crop",
        ],
        price: 320,
        location: {
          latitude: -42.8821,
          longitude: 147.3272,
          address: "Hobart, Australia",
        },
        amenities: ["WiFi", "Gym"],
        type: "Flat",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 35,
        ratings: 3.9,
        isFeatured: true,
        leaseDuration: "10 months",
        securityDeposit: 640,
        utilitiesIncluded: false,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-10T19:00:00.000Z",
        updatedAt: "2024-06-10T19:00:00.000Z",
        __v: 0,
      },
      {
        _id: "au11",
        title: "Geelong Student Apartment",
        description: "Affordable student apartment in Geelong.",
        noOfRooms: 1,
        images: [
          "https://images.unsplash.com/photo-1500673922987-e212871fec22?w=400&h=300&fit=crop",
        ],
        price: 310,
        location: {
          latitude: -38.1499,
          longitude: 144.3617,
          address: "Geelong, Australia",
        },
        amenities: ["WiFi", "Parking"],
        type: "Apartment",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 30,
        ratings: 3.8,
        isFeatured: true,
        leaseDuration: "12 months",
        securityDeposit: 620,
        utilitiesIncluded: true,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-11T20:00:00.000Z",
        updatedAt: "2024-06-11T20:00:00.000Z",
        __v: 0,
      },
      {
        _id: "au12",
        title: "Townsville Beach Studio",
        description: "Studio near the beach in Townsville.",
        noOfRooms: 1,
        images: [
          "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=400&h=300&fit=crop",
        ],
        price: 300,
        location: {
          latitude: -19.2589,
          longitude: 146.8169,
          address: "Townsville, Australia",
        },
        amenities: ["WiFi", "Gym"],
        type: "Studio",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 25,
        ratings: 3.7,
        isFeatured: true,
        leaseDuration: "9 months",
        securityDeposit: 600,
        utilitiesIncluded: false,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-12T21:00:00.000Z",
        updatedAt: "2024-06-12T21:00:00.000Z",
        __v: 0,
      },
    ],
  },
  {
    key: "usa",
    label: "USA",
    properties: [
      {
        _id: "us1",
        title: "New York Central Studio",
        description: "Studio in the heart of New York City.",
        noOfRooms: 1,
        images: [
          "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=400&h=300&fit=crop",
        ],
        price: 900,
        location: {
          latitude: 40.7128,
          longitude: -74.006,
          address: "New York, USA",
        },
        amenities: ["WiFi", "Parking", "Gym"],
        type: "Studio",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 200,
        ratings: 4.9,
        isFeatured: true,
        leaseDuration: "12 months",
        securityDeposit: 1800,
        utilitiesIncluded: true,
        petPolicy: "Pets allowed",
        createdAt: "2024-06-01T10:00:00.000Z",
        updatedAt: "2024-06-10T10:00:00.000Z",
        __v: 0,
      },
      {
        _id: "us2",
        title: "Los Angeles Beach Apartment",
        description: "Apartment near the beach in Los Angeles.",
        noOfRooms: 2,
        images: [
          "https://images.unsplash.com/photo-1466442929976-97f336a657be?w=400&h=300&fit=crop",
        ],
        price: 850,
        location: {
          latitude: 34.0522,
          longitude: -118.2437,
          address: "Los Angeles, USA",
        },
        amenities: ["WiFi", "Gym"],
        type: "Apartment",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 180,
        ratings: 4.8,
        isFeatured: true,
        leaseDuration: "10 months",
        securityDeposit: 1700,
        utilitiesIncluded: false,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-02T11:00:00.000Z",
        updatedAt: "2024-06-10T11:00:00.000Z",
        __v: 0,
      },
      {
        _id: "us3",
        title: "Chicago River Flat",
        description: "Flat with river view in Chicago.",
        noOfRooms: 1,
        images: [
          "https://images.unsplash.com/photo-1500673922987-e212871fec22?w=400&h=300&fit=crop",
        ],
        price: 700,
        location: {
          latitude: 41.8781,
          longitude: -87.6298,
          address: "Chicago, USA",
        },
        amenities: ["WiFi", "Parking"],
        type: "Flat",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 160,
        ratings: 4.7,
        isFeatured: true,
        leaseDuration: "12 months",
        securityDeposit: 1400,
        utilitiesIncluded: true,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-03T12:00:00.000Z",
        updatedAt: "2024-06-10T12:00:00.000Z",
        __v: 0,
      },
      {
        _id: "us4",
        title: "Houston Student Residence",
        description: "Student residence in Houston.",
        noOfRooms: 2,
        images: [
          "https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=400&h=300&fit=crop",
        ],
        price: 650,
        location: {
          latitude: 29.7604,
          longitude: -95.3698,
          address: "Houston, USA",
        },
        amenities: ["WiFi", "Gym"],
        type: "Residence",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 140,
        ratings: 4.6,
        isFeatured: true,
        leaseDuration: "9 months",
        securityDeposit: 1300,
        utilitiesIncluded: false,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-04T13:00:00.000Z",
        updatedAt: "2024-06-10T13:00:00.000Z",
        __v: 0,
      },
      {
        _id: "us5",
        title: "Phoenix Central Apartment",
        description: "Central apartment in Phoenix for students.",
        noOfRooms: 1,
        images: [
          "https://images.unsplash.com/photo-1466442929976-97f336a657be?w=400&h=300&fit=crop",
        ],
        price: 600,
        location: {
          latitude: 33.4484,
          longitude: -112.074,
          address: "Phoenix, USA",
        },
        amenities: ["WiFi", "Parking"],
        type: "Apartment",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 120,
        ratings: 4.5,
        isFeatured: true,
        leaseDuration: "12 months",
        securityDeposit: 1200,
        utilitiesIncluded: true,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-05T14:00:00.000Z",
        updatedAt: "2024-06-10T14:00:00.000Z",
        __v: 0,
      },
      {
        _id: "us6",
        title: "Philadelphia Student Flat",
        description: "Affordable student flat in Philadelphia.",
        noOfRooms: 2,
        images: [
          "https://images.unsplash.com/photo-1500673922987-e212871fec22?w=400&h=300&fit=crop",
        ],
        price: 580,
        location: {
          latitude: 39.9526,
          longitude: -75.1652,
          address: "Philadelphia, USA",
        },
        amenities: ["WiFi", "Gym"],
        type: "Flat",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 100,
        ratings: 4.4,
        isFeatured: true,
        leaseDuration: "10 months",
        securityDeposit: 1160,
        utilitiesIncluded: false,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-06T15:00:00.000Z",
        updatedAt: "2024-06-10T15:00:00.000Z",
        __v: 0,
      },
      {
        _id: "us7",
        title: "San Antonio River Studio",
        description: "Studio with river view in San Antonio.",
        noOfRooms: 1,
        images: [
          "https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=400&h=300&fit=crop",
        ],
        price: 570,
        location: {
          latitude: 29.4241,
          longitude: -98.4936,
          address: "San Antonio, USA",
        },
        amenities: ["WiFi", "Parking"],
        type: "Studio",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 90,
        ratings: 4.3,
        isFeatured: true,
        leaseDuration: "12 months",
        securityDeposit: 1140,
        utilitiesIncluded: true,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-07T16:00:00.000Z",
        updatedAt: "2024-06-10T16:00:00.000Z",
        __v: 0,
      },
      {
        _id: "us8",
        title: "San Diego Beach Apartment",
        description: "Apartment near the beach in San Diego.",
        noOfRooms: 2,
        images: [
          "https://images.unsplash.com/photo-1466442929976-97f336a657be?w=400&h=300&fit=crop",
        ],
        price: 560,
        location: {
          latitude: 32.7157,
          longitude: -117.1611,
          address: "San Diego, USA",
        },
        amenities: ["WiFi", "Gym"],
        type: "Apartment",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 80,
        ratings: 4.2,
        isFeatured: true,
        leaseDuration: "9 months",
        securityDeposit: 1120,
        utilitiesIncluded: false,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-08T17:00:00.000Z",
        updatedAt: "2024-06-10T17:00:00.000Z",
        __v: 0,
      },
      {
        _id: "us9",
        title: "Dallas City Studio",
        description: "Studio in Dallas city centre.",
        noOfRooms: 1,
        images: [
          "https://images.unsplash.com/photo-1500673922987-e212871fec22?w=400&h=300&fit=crop",
        ],
        price: 550,
        location: {
          latitude: 32.7767,
          longitude: -96.797,
          address: "Dallas, USA",
        },
        amenities: ["WiFi", "Parking"],
        type: "Studio",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 70,
        ratings: 4.1,
        isFeatured: true,
        leaseDuration: "12 months",
        securityDeposit: 1100,
        utilitiesIncluded: true,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-09T18:00:00.000Z",
        updatedAt: "2024-06-10T18:00:00.000Z",
        __v: 0,
      },
      {
        _id: "us10",
        title: "San Jose Student Apartment",
        description: "Affordable student apartment in San Jose.",
        noOfRooms: 2,
        images: [
          "https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=400&h=300&fit=crop",
        ],
        price: 540,
        location: {
          latitude: 37.3382,
          longitude: -121.8863,
          address: "San Jose, USA",
        },
        amenities: ["WiFi", "Gym"],
        type: "Apartment",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 60,
        ratings: 4.0,
        isFeatured: true,
        leaseDuration: "10 months",
        securityDeposit: 1080,
        utilitiesIncluded: false,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-10T19:00:00.000Z",
        updatedAt: "2024-06-10T19:00:00.000Z",
        __v: 0,
      },
      {
        _id: "us11",
        title: "Austin Central Flat",
        description: "Central flat in Austin for students.",
        noOfRooms: 1,
        images: [
          "https://images.unsplash.com/photo-1466442929976-97f336a657be?w=400&h=300&fit=crop",
        ],
        price: 530,
        location: {
          latitude: 30.2672,
          longitude: -97.7431,
          address: "Austin, USA",
        },
        amenities: ["WiFi", "Parking"],
        type: "Flat",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 50,
        ratings: 3.9,
        isFeatured: true,
        leaseDuration: "12 months",
        securityDeposit: 1060,
        utilitiesIncluded: true,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-11T20:00:00.000Z",
        updatedAt: "2024-06-11T20:00:00.000Z",
        __v: 0,
      },
      {
        _id: "us12",
        title: "Jacksonville Beach Studio",
        description: "Studio near the beach in Jacksonville.",
        noOfRooms: 1,
        images: [
          "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=400&h=300&fit=crop",
        ],
        price: 520,
        location: {
          latitude: 30.3322,
          longitude: -81.6557,
          address: "Jacksonville, USA",
        },
        amenities: ["WiFi", "Gym"],
        type: "Studio",
        available: true,
        createdBy: "admin",
        isDeleted: false,
        isVerified: true,
        views: 40,
        ratings: 3.8,
        isFeatured: true,
        leaseDuration: "9 months",
        securityDeposit: 1040,
        utilitiesIncluded: false,
        petPolicy: "No pets allowed",
        createdAt: "2024-06-12T21:00:00.000Z",
        updatedAt: "2024-06-12T21:00:00.000Z",
        __v: 0,
      },
    ],
  },
];

export const countryData = [
  {
    key: "uk",
    label: "UK",
    locations: [
      { name: "London", image: "/uk/loc1.jpg" },
      { name: "Manchester", image: "/uk/loc2.jpg" },
      { name: "Birmingham", image: "/uk/loc3.jpg" },
      { name: "Liverpool", image: "/uk/loc4.jpg" },
      { name: "Leeds", image: "/uk/loc5.jpg" },
      { name: "Sheffield", image: "/uk/loc6.jpg" },
      { name: "Bristol", image: "/uk/uni1.jpg" },
      { name: "Nottingham", image: "/uk/uni2.jpg" },
      { name: "Newcastle", image: "/uk/uni3.jpg" },
      { name: "Glasgow", image: "/uk/uni4.jpg" },
      { name: "Edinburgh", image: "/uk/uni5.jpg" },
      { name: "Cardiff", image: "/uk/uni6.jpg" },
      { name: "Southampton", image: "/uk/uni7.jpg" },
      { name: "Leicester", image: "/uk/uni8.jpg" },
      { name: "Coventry", image: "/uk/uni9.jpg" },
      { name: "Brighton", image: "/uk/uni10.jpg" },
    ],
  },
  {
    key: "australia",
    label: "Australia",
    locations: [
      { name: "Sydney", image: "/australia/loc1.jpg" },
      { name: "Melbourne", image: "/australia/loc2.jpg" },
      { name: "Brisbane", image: "/australia/loc3.jpg" },
      { name: "Perth", image: "/australia/loc4.jpg" },
      { name: "Adelaide", image: "/australia/loc5.jpg" },
      { name: "Canberra", image: "/australia/loc6.jpg" },
      { name: "Gold Coast", image: "/australia/uni1.jpg" },
      { name: "Newcastle", image: "/australia/uni2.jpg" },
      { name: "Wollongong", image: "/australia/uni3.jpg" },
      { name: "Hobart", image: "/australia/uni4.jpg" },
      { name: "Geelong", image: "/australia/uni5.jpg" },
      { name: "Townsville", image: "/australia/uni6.jpg" },
      { name: "Cairns", image: "/australia/uni7.jpg" },
      { name: "Darwin", image: "/australia/uni8.jpg" },
      { name: "Toowoomba", image: "/australia/uni9.jpg" },
      { name: "Ballarat", image: "/australia/uni10.jpg" },
    ],
  },
  {
    key: "usa",
    label: "USA",
    locations: [
      { name: "New York", image: "/usa/loc1.jpg" },
      { name: "Los Angeles", image: "/usa/loc2.jpg" },
      { name: "Chicago", image: "/usa/loc3.jpg" },
      { name: "Houston", image: "/usa/loc4.jpg" },
      { name: "Phoenix", image: "/usa/loc5.jpg" },
      { name: "Philadelphia", image: "/usa/loc6.jpg" },
      { name: "San Antonio", image: "/usa/loc7.jpg" },
      { name: "San Diego", image: "/usa/loc8.webp" },
      { name: "Dallas", image: "/usa/loc9.avif" },
      { name: "San Jose", image: "/usa/loc10.jpg" },
      { name: "Austin", image: "/usa/loc11.jpg" },
      { name: "Jacksonville", image: "/usa/loc12.jpg" },
      { name: "Fort Worth", image: "/usa/loc13.avif" },
      { name: "Columbus", image: "/usa/loc14.avif" },
      { name: "Charlotte", image: "/usa/loc15.jpg" },
      { name: "San Francisco", image: "/usa/loc16.jpg" },
    ],
  },
];

export const featuredBlogs = [
  {
    id:4,
    date: "17/6/25",
    image:"/uk/uni4.jpg",
    meta_description:
      "Looking for the best suburbs in Australia for student living? Discover 7 affordable, safe, and well-connected neighborhoods near major universities, with insights on rent, transport, and lifestyle.",
    title: "Top 7 Student-Friendly Suburbs in Australia for Affordable Living",
    keywords: [
      "best suburbs for students Australia",
      "cheap student accommodation",
      "safe student neighborhoods",
      "affordable student housing Australia",
    ],
    introduction:
      "When moving to Australia for university, students often find themselves overwhelmed by the cost of living, housing types, and neighborhood options. For many, the challenge is not just about finding a place to stay, but about securing the right suburb that fits their lifestyle and budget without compromising on safety or access to campus.\n\nThis guide outlines seven student-friendly suburbs across major Australian cities. These areas offer a balance of affordability, transport convenience, local amenities, and vibrant communities, helping students make smart choices early on.",
    suburbs: [
      {
        name: "Kensington",
        city: "Sydney",
        near_university: "UNSW",
        average_rent_per_week: "AUD $370–$480",
        highlights: [
          "Close to UNSW",
          "Modern apartments and share houses",
          "Local restaurants",
        ],
        transport: ["Light rail", "Bus services"],
        tenancy_resource: "NSW Fair Trading",
      },
      {
        name: "Carlton",
        city: "Melbourne",
        near_university: "University of Melbourne, RMIT",
        average_rent_per_week: "AUD $320–$440",
        highlights: [
          "Proximity to campus",
          "Lygon Street food hub",
          "Cultural district",
        ],
        transport: ["Multiple tram lines"],
        tenancy_resource: "Consumer Affairs Victoria",
      },
      {
        name: "St Lucia",
        city: "Brisbane",
        near_university: "University of Queensland",
        average_rent_per_week: "AUD $300–$420",
        highlights: [
          "Green spaces",
          "Quiet residential setting",
          "Riverfront campus access",
        ],
        transport: ["Bus routes", "CityCat ferry"],
        tenancy_resource: "Residential Tenancies Authority QLD",
      },
      {
        name: "North Adelaide",
        city: "Adelaide",
        near_university: "University of Adelaide, UniSA",
        average_rent_per_week: "AUD $260–$370",
        highlights: [
          "Historic architecture",
          "Cafés and parks",
          "Walkable streets",
        ],
        transport: ["Free city loop buses", "Cycle-friendly roads"],
        tenancy_resource: "SA Gov Tenancy Advice",
      },
      {
        name: "Brunswick",
        city: "Melbourne",
        near_university: "RMIT, La Trobe, University of Melbourne",
        average_rent_per_week: "AUD $290–$410",
        highlights: ["Music scene", "Art spaces", "Affordable dining"],
        transport: ["Sydney Road tram lines", "Upfield train"],
        note: "Competitive market—use platforms like GoUniNest",
      },
      {
        name: "Subiaco",
        city: "Perth",
        near_university: "UWA, Curtin University",
        average_rent_per_week: "AUD $280–$390",
        highlights: [
          "Kings Park proximity",
          "Cafés and markets",
          "Quiet study spots",
        ],
        transport: ["Subiaco train station", "Transperth bus routes"],
        tenancy_resource: "WA Consumer Protection",
      },
      {
        name: "West End",
        city: "Brisbane",
        near_university: "Griffith University, QUT",
        average_rent_per_week: "AUD $310–$430",
        highlights: [
          "Alternative vibe",
          "International cuisine",
          "Community events",
        ],
        transport: ["South Brisbane train", "CityGlider buses"],
        note: "Many listings include utilities and Wi‑Fi",
      },
    ],
    key_points_to_consider: [
      "Commute time to your university during peak hours",
      "Proximity to essential services such as grocery stores, healthcare, and study spaces",
      "Availability of part‑time job opportunities within the suburb or nearby",
      "Local student population density for better deals and safety",
      "Access to verified housing platforms like GoUniNest to avoid scams",
    ],
    conclusion:
      "Living in the right suburb can make a huge difference in how students experience university life in Australia. Whether it's the academic focus of Carlton, the creative energy of Brunswick, or the calm green feel of St Lucia, each suburb offers something unique. By balancing affordability, safety, and location, students can enjoy a vibrant lifestyle while staying within budget.\n\nFor students looking to simplify their housing journey, GoUniNest provides a trusted platform with listings tailored to student needs. Verified properties, clear lease terms, and student-friendly support make it easier to settle into the perfect neighborhood. Explore GoUniNest and take the guesswork out of finding your next home in Australia.",
  },
  {
    id:5,
    date: "17/6/25",
    image:"/uk/uni5.jpg",
    meta_description:
      "Renting in Australia as an international student? Learn key rental tips, legal rights, how to avoid scams, and what to inspect before signing a lease. A must-read guide for overseas students in 2025.",
    title:
      "What International Students Should Know Before Renting in Australia",
    keywords: [
      "international student rental tips",
      "renting in Australia for foreigners",
      "student housing Australia",
      "student lease guide Australia",
      "tenancy rights for overseas students",
    ],
    introduction:
      "Renting a place to live is one of the most important tasks international students face after receiving their university offer. For many, this is the first time navigating a foreign housing system. Understanding how the rental process works in Australia can save time, money, and unnecessary stress.\n\nThis guide walks through what every international student should know before renting in Australia, from spotting scams and reading lease agreements to knowing your legal rights and what to inspect during a property visit.",
    sections: [
      {
        title: "1. Understand Your Rental Rights as a Student",
        content:
          "Australia has strong tenancy laws that protect all renters, including international students. These rights vary slightly by state, but common protections include a written lease agreement, the right to a safe, clean, functional home, limits on rent increases, and bond refund guarantees.",
        state_bodies: [
          "NSW Fair Trading",
          "Tenants Victoria",
          "Residential Tenancies Authority QLD",
          "Consumer and Business Services SA",
          "Consumer Protection WA",
        ],
        note: "Always read your tenancy agreement carefully and don’t feel pressured to sign without understanding the terms.",
      },
      {
        title: "2. Know What the Bond Is and How It Works",
        content:
          "The bond is a security deposit equal to typically four weeks’ rent, paid upfront and held by a government authority. It’s fully refundable if there are no damages or unpaid rent.",
        bond_authorities: [
          "Rental Bond Board NSW",
          "RTBA Victoria",
          "RTA QLD Bonds",
        ],
        warning:
          "If a landlord asks for cash directly or refuses to lodge your bond, it’s a red flag—always ask for an official receipt.",
      },
      {
        title: "3. Watch Out for Rental Scams",
        warning_signs: [
          "Payment requested before you’ve seen the property",
          "Fake listings with very low rent",
          "No formal lease agreement",
          "Refusal to meet in person or via live video",
          "Pressure to decide quickly",
        ],
        protection:
          "Use reliable platforms like GoUniNest and cross-check listings on realestate.com.au or Domain.",
      },
      {
        title: "4. Inspect the Property Thoroughly",
        checklist: [
          "Mould or water damage",
          "Working smoke alarms",
          "Secure door and window locks",
          "Proper lighting and ventilation",
          "Cleanliness of kitchen and bathroom",
          "Condition of furniture and appliances",
        ],
        tip: "Take photos before moving in and insist on a live video walkthrough if renting sight-unseen.",
      },
      {
        title: "5. Understand the Lease Terms",
        lease_items: [
          "Duration (e.g., 6‑month or 12‑month lease)",
          "Rent due dates and payment methods",
          "Inclusions (utilities, internet)",
          "Break clause details",
          "Inspection frequency and notice requirements",
        ],
        advice:
          "Consult your university’s student services or a local tenancy advice center if unsure about any clause.",
      },
      {
        title: "6. Know Your Support Channels",
        resources: [
          "Study Australia’s Accommodation Guide",
          "Redfern Legal Centre (NSW)",
          "Tenancy WA",
          "International Student Legal Service (Victoria)",
        ],
        suggestion:
          "Speak with your university’s international office for housing guidance and legal referrals.",
      },
    ],
    key_tips_before_signing: [
      "Start your housing search early, especially before semester start",
      "Use trusted platforms like GoUniNest to avoid fake listings",
      "Never pay in cash or transfer money without documentation",
      "Ensure your bond is lodged legally with the appropriate authority",
      "Check state-specific rental laws",
      "Inspect the property in person or via live walkthrough",
    ],
    conclusion:
      "Renting in Australia as an international student can be smooth and safe with the right preparation. Understanding your rights, recognizing red flags, and relying on verified platforms and legal resources is essential. Use specialist platforms like GoUniNest for transparent leases and tailored support, protecting both your housing and academic journey.",
  },
  {
    id:1,
    date: "17/6/25",
    image:"/uk/uni7.jpg",
    meta_description:
      "Setting up your student room in Australia? Use this essential checklist for bedding, kitchen items, electronics, and décor tips. Perfect for international and first-year students in 2025.",
    title:
      "How to Set Up Your First Student Room in Australia: Essentials Checklist",
    keywords: [
      "student room setup Australia",
      "student essentials checklist",
      "dorm room must-haves",
      "first-year university packing list",
      "student life Australia",
    ],
    introduction:
      "Starting university in Australia brings excitement, new friendships, and the chance to live independently, but setting up your student room can be overwhelming. Whether you're staying in an on‑campus dorm or renting off‑campus housing, creating a comfortable, functional space is essential.\n\nThis guide offers a practical checklist to help you move in with confidence. It covers everything from bedding and electronics to kitchenware and study supplies, with suggestions from reliable Australian stores to make your setup hassle‑free.",
    sections: [
      {
        title: "1. Bedding Essentials",
        items: [
          "Fitted sheet and flat sheet",
          "Quilt (duvet) and quilt cover",
          "Pillows (x2) and pillowcases",
          "Mattress protector",
          "Blanket or throw for colder months",
        ],
        stores: ["Kmart", "Target Australia", "IKEA Australia"],
        notes:
          "Many students also purchase full bedding kits online before arrival through The Oodie or Myer.",
      },
      {
        title: "2. Study Setup",
        items: [
          "Desk lamp with adjustable lighting",
          "Stationery kit: pens, highlighters, sticky notes, notepads",
          "Laptop or tablet with charger",
          "Surge‑protected power board",
          "Noise‑cancelling headphones",
        ],
        stores: ["Officeworks", "JB Hi‑Fi"],
        notes: "Look for student discounts on UNiDAYS.",
      },
      {
        title: "3. Kitchen Must‑Haves",
        items: [
          "Microwave‑safe plates and bowls",
          "Cutlery set",
          "Non‑stick frying pan and small saucepan",
          "Chopping board",
          "Reusable water bottle and coffee cup",
          "Dish soap, sponge, and tea towels",
          "Food storage containers",
        ],
        stores: ["Big W", "Coles Online"],
        notes:
          "Basic kitchen starter kits are often available as delivery packages.",
      },
      {
        title: "4. Bathroom Supplies",
        items: [
          "Shower caddy",
          "Bath towel and face towel",
          "Toiletries (toothbrush, toothpaste, soap, shampoo, etc.)",
          "Toilet paper",
          "Laundry basket and detergent",
        ],
        stores: ["Chemist Warehouse", "Priceline"],
      },
      {
        title: "5. Room Comfort and Décor",
        items: [
          "Photos of family and friends",
          "Small indoor plants or artificial greenery",
          "Throw pillows and rugs",
          "Command hooks and adhesive strips",
          "Air freshener or essential oil diffuser",
        ],
        stores: ["Typo", "IKEA Australia"],
      },
      {
        title: "6. Personal Safety and Extras",
        items: [
          "Portable fan or small heater",
          "Small toolkit or screwdriver set",
          "First aid kit",
          "Umbrella",
          "Backpack or day bag",
        ],
        notes:
          "Check accommodation rules for electrical items; these extras are handy in extreme weather.",
      },
    ],
    where_to_shop: [
      "Kmart Australia",
      "IKEA Australia",
      "Officeworks",
      "The Reject Shop",
      "Target Australia",
      "GoUniNest (for accommodation listings and move‑in guidance)",
    ],
    conclusion:
      "Setting up your first student room in Australia can feel like a big task, but with a little planning and a solid checklist, it becomes an exciting step toward independence. From kitchen gear to cozy blankets, each item helps transform your space into a personal haven where you can rest, study, and grow.\n\nFor students who haven’t secured housing yet or want help with move‑in ready listings, GoUniNest is a trusted platform that simplifies student accommodation across Australia. With verified rentals and move‑in tips, it's a great starting point for your new journey.\n\nMake your room reflect who you are. After all, this isn’t just a place to sleep—it’s your first home away from home.",
  }
]
