name: Deploy Next.js to GCP Cloud Run

on:
  push:
    branches: [master, main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON_PROD }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: gouninest

      - name: Authenticate Docker with GCR
        run: gcloud auth configure-docker gcr.io

      - name: Build Docker Image
        run: docker build -t gcr.io/gouninest/gouninest-web-image:latest -f Dockerfiles/Dockerfile .

      - name: Push Docker Image to GCR
        run: docker push gcr.io/gouninest/gouninest-web-image:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy gouninest-web-app \
            --image gcr.io/gouninest/gouninest-web-image:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --port 3000